# This is a basic workflow to build and deploy your open textbook with Bookdown.

on:
  push:
    branches: 
      - main

# Courtesy of https://github.com/nulib-oer/empirical-methods-polisci/blob/main/.github/workflows/preview.yml

name: renderbook

jobs:
  bookdown:
    name: Render-Book
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      #- uses: r-lib/actions/setup-pandoc@v1
      #- name: Install TinyTeX
      #  run: Rscript -e 'tinytex::install_tinytex()'
      - name: Install R Markdown and Bookdown packages
        run: Rscript -e 'install.packages(c("rmarkdown","bookdown","magick","pdftools"))'
      - name: Build Book
        run: |
          set -ev
          Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::tufte_html_book')"
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book
